/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

/**
 *
 * @author user
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdKategori = new javax.swing.JButton();
        cmdPetugas = new javax.swing.JButton();
        cmdTransaksi = new javax.swing.JButton();
        cmdLaporan = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        cmdObat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APOTEK ZAGITA");

        cmdKategori.setBackground(new java.awt.Color(255, 204, 255));
        cmdKategori.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmdKategori.setForeground(new java.awt.Color(255, 0, 204));
        cmdKategori.setText("KATEGORI");
        cmdKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKategoriMouseClicked(evt);
            }
        });
        cmdKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKategoriActionPerformed(evt);
            }
        });

        cmdPetugas.setBackground(new java.awt.Color(255, 204, 255));
        cmdPetugas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmdPetugas.setForeground(new java.awt.Color(255, 0, 204));
        cmdPetugas.setText("PETUGAS");
        cmdPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdPetugasMouseClicked(evt);
            }
        });
        cmdPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPetugasActionPerformed(evt);
            }
        });

        cmdTransaksi.setBackground(new java.awt.Color(255, 204, 255));
        cmdTransaksi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmdTransaksi.setForeground(new java.awt.Color(255, 0, 204));
        cmdTransaksi.setText("TRANSAKSI");
        cmdTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdTransaksiMouseClicked(evt);
            }
        });
        cmdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTransaksiActionPerformed(evt);
            }
        });

        cmdLaporan.setBackground(new java.awt.Color(255, 204, 255));
        cmdLaporan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmdLaporan.setForeground(new java.awt.Color(255, 0, 204));
        cmdLaporan.setText("LAPORAN");
        cmdLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdLaporanMouseClicked(evt);
            }
        });
        cmdLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLaporanActionPerformed(evt);
            }
        });

        cmdKeluar.setBackground(new java.awt.Color(255, 204, 255));
        cmdKeluar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmdKeluar.setForeground(new java.awt.Color(255, 0, 204));
        cmdKeluar.setText("KELUAR");
        cmdKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKeluarMouseClicked(evt);
            }
        });

        cmdObat.setBackground(new java.awt.Color(255, 204, 255));
        cmdObat.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmdObat.setForeground(new java.awt.Color(255, 0, 204));
        cmdObat.setText("OBAT");
        cmdObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdObatMouseClicked(evt);
            }
        });
        cmdObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdObatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdTransaksi)
                    .addComponent(cmdLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdKategori)
                    .addComponent(cmdTransaksi)
                    .addComponent(cmdObat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdPetugas)
                    .addComponent(cmdLaporan)
                    .addComponent(cmdKeluar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdObatActionPerformed

    private void cmdObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdObatMouseClicked
        // TODO add your handling code here:
        new obat().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdObatMouseClicked

    private void cmdKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKeluarMouseClicked
        new Login().setVisible(true);
    }//GEN-LAST:event_cmdKeluarMouseClicked

    private void cmdLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLaporanActionPerformed

    }//GEN-LAST:event_cmdLaporanActionPerformed

    private void cmdLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdLaporanMouseClicked
        // TODO add your handling code here:
        new Laporan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdLaporanMouseClicked

    private void cmdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTransaksiActionPerformed

    }//GEN-LAST:event_cmdTransaksiActionPerformed

    private void cmdTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTransaksiMouseClicked
        // TODO add your handling code here:
        new transaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdTransaksiMouseClicked

    private void cmdPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPetugasActionPerformed

    }//GEN-LAST:event_cmdPetugasActionPerformed

    private void cmdPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPetugasMouseClicked
        // TODO add your handling code here:
        new petugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdPetugasMouseClicked

    private void cmdKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdKategoriActionPerformed

    private void cmdKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKategoriMouseClicked
        new kategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdKategoriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdKategori;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdLaporan;
    private javax.swing.JButton cmdObat;
    private javax.swing.JButton cmdPetugas;
    private javax.swing.JButton cmdTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
